# Generated by Django 4.0.4 on 2022-05-12 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soumissionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soumission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cahierCharge', models.FileField(upload_to='')),
                ('classification', models.TextField()),
                ('nbMaterial', models.BigIntegerField()),
                ('nbSalarie', models.BigIntegerField()),
                ('delai', models.DateField()),
                ('extraitRole', models.FileField(upload_to='')),
                ('nCnas', models.BigIntegerField()),
                ('prix', models.FloatField()),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soumissionnaire.lot')),
                ('soumissionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soumissionnaire.soumissionnaire')),
            ],
        ),
    ]
