# Generated by Django 4.0.4 on 2022-05-12 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soumissionnaire', '0001_initial'),
        ('soumission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soumission',
            name='offre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='soumissionnaire.offre'),
            preserve_default=False,
        ),
    ]
