# Generated by Django 4.0.4 on 2022-05-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soumission', '0003_alter_soumission_cahiercharge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soumission',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
