# Generated by Django 4.0.4 on 2022-05-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soumission', '0004_alter_soumission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soumission',
            name='cahierCharge',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='soumission',
            name='classification',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='soumission',
            name='delai',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='soumission',
            name='extraitRole',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='soumission',
            name='nCnas',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='soumission',
            name='nbMaterial',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='soumission',
            name='nbSalarie',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='soumission',
            name='prix',
            field=models.FloatField(),
        ),
    ]
