# Generated by Django 4.0.4 on 2022-06-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soumission', '0005_alter_soumission_cahiercharge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soumission',
            name='cahierCharge',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='soumission',
            name='extraitRole',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='soumission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
