# Generated by Django 4.0.4 on 2022-06-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soumission', '0006_alter_soumission_cahiercharge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soumission',
            name='prix',
            field=models.CharField(max_length=100),
        ),
    ]
