# Generated by Django 4.0.5 on 2022-06-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soumission', '0008_alter_soumission_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soumission',
            name='delai',
            field=models.BigIntegerField(),
        ),
    ]
