# Generated by Django 4.0.5 on 2022-06-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soumission', '0009_alter_soumission_delai'),
    ]

    operations = [
        migrations.AddField(
            model_name='soumission',
            name='soumissionnaireName',
            field=models.CharField(default='name1', max_length=30),
            preserve_default=False,
        ),
    ]
