# Generated by Django 4.0.4 on 2022-05-12 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Soumissionnaire',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('is_valid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soumissionnaire.offre')),
            ],
        ),
    ]
