# Generated by Django 4.0.4 on 2022-06-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soumissionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='mongoid',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offre',
            name='mongoid',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offre',
            name='name',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soumissionnaire',
            name='mongoid',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='soumissionnaire',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
