# Generated by Django 4.0.4 on 2022-06-11 22:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('soumissionnaire', '0002_lot_mongoid_offre_mongoid_offre_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='d_Day',
            field=models.DateField(default=datetime.datetime(2022, 6, 11, 22, 40, 45, 657799, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
